thingspeak:
  channel_id: 3175956
  read_api_key: "TEFO1R0JKX7O2MMM"
  field_temp: 1
  field_hum: 2
  results: 10000


nombre_cliente: "Mi estaci√≥n DHT22"
salida_informes: "outputs/informes"
salida_graficos: "outputs/graficos"
nota_legal_path: "docs/nota_legal_orientativo.txt"
umbral_alerta_temp: 30.0
franja_resumen_horas: 2
intervalo_min: 0.33
